const ActionTypes = {
  CATEGORIES_ALL_REQ: "CATEGORIES_ALL_REQ",
  CATEGORIES_ALL_OK: "CATEGORIES_ALL_OK",
  CATEGORIES_ALL_X: "CATEGORIES_ALL_X",

  CATEGORY_ADD_REQ: "CATEGORY_ADD_REQ",
  CATEGORY_ADD_OK: "CATEGORY_ADD_OK",
  CATEGORY_ADD_X: "CATEGORY_ADD_X"
};
export default ActionTypes;
